package View.enums;

public enum Validations {
    EMPTY_FIELD,
    INVALID_USERNAME,
    DUPLICATE_USERNAME,
    INVALID_FLAG,
    DUPLICATE_EMAIL,
    INVALID_EMAIL,
    USERNAME_CHANGE_SUCCESSFUL,
    NICKNAME_CHANGE_SUCCESSFUL,
    EMAIL_CHANGE_SUCCESSFUL,
    SLOGAN_CHANGE_SUCCESSFUL,
    SLOGAN_CHANGED_TO_RANDOM,
    INCORRECT_PASSWORD,
    NOT_NEW_PASSWORD,
    PASSWORD_CHANGE_SUCCESSFUL,
    WEAK_PASSWORD,
    INVALID_CONFIRM_FOR_RANDOM,
    PASSWORD_CHANGED_TO_RANDOM,
}
